use_frameworks!

platform :ios, '10.0'

target 'EventTrackingLibrary_Example' do
  pod 'EventTrackingLibrary', :path => '../'

  target 'EventTrackingLibrary_Tests' do
    inherit! :search_paths

    
  end
end
